/**
 * Agent-facing project files scaffolded into every widget directory:
 *
 *   AGENTS.md  — the complete widget-authoring guide (from
 *                `@eeko/sdk/authoring-guide`, the platform's single source of
 *                truth) under a CLI-specific workflow header.
 *   CLAUDE.md  — points Claude Code at AGENTS.md.
 *   .mcp.json  — connects MCP-capable agents to Eeko's platform MCP server
 *                (account-aware discovery: `describe_trigger` etc.).
 *
 * Files are never silently overwritten — `eeko agents-md --force` regenerates.
 */

import { readFileSync } from 'fs'
import { readFile, writeFile, access } from 'fs/promises'
import path from 'path'
import { fileURLToPath } from 'url'
import { AUTHORING_GUIDE, AUTHORING_GUIDE_VERSION } from '@eeko/sdk/authoring-guide'

export const MCP_PLATFORM_URL = 'https://mcp.eeko.app/mcp'

function cliVersion(): string {
  // dist/index.js sits one level below the package root; src/utils/ two. Walk
  // up until the CLI's own package.json is found.
  let dir = path.dirname(fileURLToPath(import.meta.url))
  for (let i = 0; i < 4; i++) {
    dir = path.dirname(dir)
    try {
      const pkg = JSON.parse(readFileSync(path.join(dir, 'package.json'), 'utf-8')) as {
        name?: string
        version?: string
      }
      if (pkg.name === '@eeko/cli' && pkg.version) return pkg.version
    } catch {
      /* keep walking */
    }
  }
  throw new Error('Could not locate the @eeko/cli package.json')
}

/** Stamp parsed back out of AGENTS.md to detect staleness on clone. */
export function readGuideVersionStamp(content: string): string | null {
  const match = content.match(/@eeko\/sdk v(\d+\.\d+\.\d+(?:-[\w.]+)?)/)
  return match ? match[1] : null
}

export function renderAgentsMd(): string {
  return `<!-- Generated by @eeko/cli v${cliVersion()} from @eeko/sdk v${AUTHORING_GUIDE_VERSION}.
     Regenerate with: eeko agents-md --force (do not hand-edit; edits are lost on regeneration). -->

# Working in an Eeko project

An Eeko **project** is an authoring/marketplace unit with two optional, first-class sides:

- a **widget** — a \`uc-{id}\` git artifact in \`widget/\` — the visual overlay, and
- an **automation** — an \`au-{id}\` git artifact in \`automation/\` — the trigger → action wiring that fires it.

A project can have the widget, the automation, both, or neither — the two sides are **independent**. Each side is its own git repo whose \`draft\` branch is the working copy and whose \`main\` branch renders/runs live. \`eeko.config.json\` ties each directory to the platform — never delete or edit it.

## Layout

\`\`\`
my-project/
├── eeko.config.json   # the project (projectId, owner)
├── widget/            # optional — the widget side
└── automation/        # optional — the automation side
\`\`\`

## The triad (creating things)

1. \`eeko project init <name> [--account <slug>]\` — create the project. Personal by default, or under a merchant account with \`--account\`. The owner is set ONCE here; both sides inherit it.
2. \`eeko widget init\` — from the project root, add the widget side (clones \`widget/\`, scaffolds a template).
3. \`eeko automation init\` — from the project root, add the automation side (clones \`automation/\`; wires the sibling widget if there is one, otherwise scaffolds a utility automation).

(\`eeko init\` is a shortcut that makes a standalone widget with no project — use the triad when you want a project, an automation, or both.)

## The widget loop (run inside \`widget/\`)

1. Edit \`widget.json\` / \`index.html\` / \`styles.css\` / \`script.js\` (the full contract is below).
2. \`eeko build --json\` — structured validation (manifest schema, interactions, contract lint). Treat errors like failing tests; iterate until \`ok: true\`.
3. \`eeko dev --no-open\` (runs headless; leave it running) then, from another shell, \`eeko test trigger\` / \`eeko test chat\` / \`eeko test all-chat\` — simulated events with production payload shapes. The dev server prints its URL; \`.eeko-dev.json\` records the live ports.
4. \`eeko publish\` — commits and pushes to the \`draft\` ref for human review in Studio. \`eeko promote\` (human) takes it to \`main\`.

## The automation loop (run inside \`automation/\`)

1. Edit \`automation.json\` — a \`{ triggers, conditions?, actions }\` config. Pick the trigger you want; use \`describe_trigger\` (MCP) for its exact shape and \`list_action_types\` for action shapes. **Leave \`channelId\`/\`channelName\` empty** and reference no personal connections — catalog automations are *shells*, bound to the installer at install time. If the project has a widget, keep the \`trigger_component\` action pointing at it; for a utility automation, use a real action (moderation, chat, variable, …) instead.
2. \`eeko build\` validates it (field-level errors if the shape is wrong).
3. \`eeko publish\` makes the automation live. Automations are **save = live** — there is no separate promote for them (a catalog shell can't fire until a streamer installs and binds it, so "live" is harmless). The widget side still uses draft → promote.

## Marketplace images (optional)

A catalog project can carry a **thumbnail** (browse card) and a **gallery** (detail page, up to 10 images). From the project root:

- \`eeko project thumbnail <file-or-url>\` — set the cover image (a local PNG/JPG/WebP/GIF is uploaded automatically, then assigned; or pass an existing asset URL). \`--clear\` removes it.
- \`eeko project gallery <files-or-urls...>\` — set the gallery (replaces it; \`--append\` adds to it, \`--clear\` empties it).
- \`eeko asset upload <file> --public\` — the lower-level primitive; uploads an image and prints its URL.

SVG is not allowed; images are uploaded public so the marketplace can render them. Only add images you were given or told to use — don't invent cover art.

## Human-only steps — never run these yourself

- \`eeko promote\` (draft → main, i.e. going live) for the **widget** is the owner's decision.
- \`eeko project release\` (cut a release) is the owner's call — only run it if explicitly asked. A marketplace release is reviewed and approved by an Eeko admin before it's public; \`eeko project release --private\` skips review and is shared directly by email instead (never listed publicly).

Stop after \`eeko publish\` (each side you touched) and report what you built.

## MCP

\`.mcp.json\` connects you to Eeko's platform MCP server (${MCP_PLATFORM_URL}). Use \`describe_trigger\` for the exact data points a platform trigger carries before binding payload fields the guide doesn't list, and \`list_action_types\` for action shapes when editing \`automation.json\`. Discovery tools (\`list_trigger_types\`, \`list_accounts\`, \`list_user_assets\`) cover what exists on the account. If the MCP server is unreachable, the guide's documented common dataPoints are a safe baseline — prefer them over invented field names.

---

${AUTHORING_GUIDE}`
}

export function renderClaudeMd(): string {
  return `@AGENTS.md

The file above is the complete authoring guide for this Eeko widget project — the contract, the validation loop, and the boundaries. Follow it.
`
}

export function renderMcpJson(): string {
  return (
    JSON.stringify(
      {
        mcpServers: {
          'eeko-platform': { type: 'http', url: MCP_PLATFORM_URL },
        },
      },
      null,
      2
    ) + '\n'
  )
}

const GITIGNORE_LINES = ['node_modules/', '.eeko-dev.json']

export interface WriteAgentFilesResult {
  written: string[]
  skipped: string[]
}

/**
 * Write AGENTS.md, CLAUDE.md and .mcp.json into `dir` (plus a .gitignore for
 * the dev descriptor). Existing files are skipped unless `force` — never
 * silently overwrite something the author may have edited.
 */
export async function writeAgentFiles(
  dir: string,
  opts: { force?: boolean } = {}
): Promise<WriteAgentFilesResult> {
  const files: Array<[string, string]> = [
    ['AGENTS.md', renderAgentsMd()],
    ['CLAUDE.md', renderClaudeMd()],
    ['.mcp.json', renderMcpJson()],
  ]

  const written: string[] = []
  const skipped: string[] = []

  for (const [name, content] of files) {
    const target = path.join(dir, name)
    const exists = await access(target).then(
      () => true,
      () => false
    )
    if (exists && !opts.force) {
      skipped.push(name)
      continue
    }
    await writeFile(target, content)
    written.push(name)
  }

  // .gitignore: append missing lines rather than overwrite.
  const gitignorePath = path.join(dir, '.gitignore')
  const existing = await readFile(gitignorePath, 'utf-8').catch(() => '')
  const missing = GITIGNORE_LINES.filter((line) => !existing.split('\n').includes(line))
  if (missing.length > 0) {
    const next = existing.length > 0 && !existing.endsWith('\n') ? existing + '\n' : existing
    await writeFile(gitignorePath, next + missing.join('\n') + '\n')
    written.push('.gitignore')
  }

  return { written, skipped }
}
