/**
 * Agent-facing project files scaffolded into every widget directory:
 *
 *   AGENTS.md  — the complete widget-authoring guide (from
 *                `@eeko/sdk/authoring-guide`, the platform's single source of
 *                truth) under a CLI-specific workflow header.
 *   CLAUDE.md  — points Claude Code at AGENTS.md.
 *   .mcp.json  — connects MCP-capable agents to Eeko's platform MCP server
 *                (account-aware discovery: `describe_trigger` etc.).
 *
 * Files are never silently overwritten — `eeko agents-md --force` regenerates.
 */

import { readFileSync } from 'fs'
import { readFile, writeFile, access } from 'fs/promises'
import path from 'path'
import { fileURLToPath } from 'url'
import { AUTHORING_GUIDE, AUTHORING_GUIDE_VERSION } from '@eeko/sdk/authoring-guide'

export const MCP_PLATFORM_URL = 'https://mcp.eeko.app/mcp'

function cliVersion(): string {
  // dist/index.js sits one level below the package root; src/utils/ two. Walk
  // up until the CLI's own package.json is found.
  let dir = path.dirname(fileURLToPath(import.meta.url))
  for (let i = 0; i < 4; i++) {
    dir = path.dirname(dir)
    try {
      const pkg = JSON.parse(readFileSync(path.join(dir, 'package.json'), 'utf-8')) as {
        name?: string
        version?: string
      }
      if (pkg.name === '@eeko/cli' && pkg.version) return pkg.version
    } catch {
      /* keep walking */
    }
  }
  throw new Error('Could not locate the @eeko/cli package.json')
}

/** Stamp parsed back out of AGENTS.md to detect staleness on clone. */
export function readGuideVersionStamp(content: string): string | null {
  const match = content.match(/@eeko\/sdk v(\d+\.\d+\.\d+(?:-[\w.]+)?)/)
  return match ? match[1] : null
}

export function renderAgentsMd(): string {
  return `<!-- Generated by @eeko/cli v${cliVersion()} from @eeko/sdk v${AUTHORING_GUIDE_VERSION}.
     Regenerate with: eeko agents-md --force (do not hand-edit; edits are lost on regeneration). -->

# Working in this Eeko widget project

This directory is one Eeko widget: a git repo whose \`draft\` branch is the working copy and whose \`main\` branch renders live. \`eeko.config.json\` ties it to the widget on the Eeko platform — never delete or edit it.

## The loop

1. Edit \`widget.json\` / \`index.html\` / \`styles.css\` / \`script.js\` (the full contract is below).
2. \`eeko build --json\` — structured validation (manifest schema, interactions, contract lint). Treat errors like failing tests; iterate until \`ok: true\`.
3. \`eeko dev --no-open\` (runs headless; leave it running) then, from another shell, \`eeko test trigger\` / \`eeko test chat\` / \`eeko test all-chat\` — simulated events with production payload shapes. The dev server prints its URL; \`.eeko-dev.json\` records the live ports.
4. \`eeko publish\` — commits and pushes to the \`draft\` ref for human review in Studio.

## Human-only steps — never run these yourself

- \`eeko promote\` (draft → main, i.e. going live) is the owner's decision.
- Marketplace releases are cut in the merchant app, never from this directory.

Stop after \`eeko publish\` and report what you built.

## MCP

\`.mcp.json\` connects you to Eeko's platform MCP server (${MCP_PLATFORM_URL}). Use \`describe_trigger\` for the exact data points a platform trigger carries — never guess payload field names. Discovery tools (\`list_trigger_types\`, \`list_action_types\`, \`list_user_assets\`) cover what exists on the account.

---

${AUTHORING_GUIDE}`
}

export function renderClaudeMd(): string {
  return `@AGENTS.md

The file above is the complete authoring guide for this Eeko widget project — the contract, the validation loop, and the boundaries. Follow it.
`
}

export function renderMcpJson(): string {
  return (
    JSON.stringify(
      {
        mcpServers: {
          'eeko-platform': { type: 'http', url: MCP_PLATFORM_URL },
        },
      },
      null,
      2
    ) + '\n'
  )
}

const GITIGNORE_LINES = ['node_modules/', '.eeko-dev.json']

export interface WriteAgentFilesResult {
  written: string[]
  skipped: string[]
}

/**
 * Write AGENTS.md, CLAUDE.md and .mcp.json into `dir` (plus a .gitignore for
 * the dev descriptor). Existing files are skipped unless `force` — never
 * silently overwrite something the author may have edited.
 */
export async function writeAgentFiles(
  dir: string,
  opts: { force?: boolean } = {}
): Promise<WriteAgentFilesResult> {
  const files: Array<[string, string]> = [
    ['AGENTS.md', renderAgentsMd()],
    ['CLAUDE.md', renderClaudeMd()],
    ['.mcp.json', renderMcpJson()],
  ]

  const written: string[] = []
  const skipped: string[] = []

  for (const [name, content] of files) {
    const target = path.join(dir, name)
    const exists = await access(target).then(
      () => true,
      () => false
    )
    if (exists && !opts.force) {
      skipped.push(name)
      continue
    }
    await writeFile(target, content)
    written.push(name)
  }

  // .gitignore: append missing lines rather than overwrite.
  const gitignorePath = path.join(dir, '.gitignore')
  const existing = await readFile(gitignorePath, 'utf-8').catch(() => '')
  const missing = GITIGNORE_LINES.filter((line) => !existing.split('\n').includes(line))
  if (missing.length > 0) {
    const next = existing.length > 0 && !existing.endsWith('\n') ? existing + '\n' : existing
    await writeFile(gitignorePath, next + missing.join('\n') + '\n')
    written.push('.gitignore')
  }

  return { written, skipped }
}
